// Thin TypeScript wrapper around the WASM engine. All graph work
// crosses the boundary into Rust; the rest of the web app talks to
// this wrapper, never to the raw wasm-bindgen output.

import init, {
  Engine as WasmEngine,
  MiniRuntime as WasmMiniRuntime,
  engine_version,
} from './wasm/ecto_engine'

let initialized = false

export async function ensureEngineReady(): Promise<void> {
  if (initialized) return
  // Vite serves the .wasm file at this URL when imported as ?url.
  // The default `init()` call uses the path generated by wasm-bindgen.
  await init()
  initialized = true
  // eslint-disable-next-line no-console
  console.log('[ecto] engine v' + engine_version() + ' loaded')
}

export type FileBlob = { path: string; content: string }

export type GraphNode = {
  id: string
  projectId?: string
  type: string
  name: string
  data: Record<string, any>
  source?: { filePath?: string; startLine?: number; endLine?: number }
}

export type GraphEdge = {
  id: string
  projectId?: string
  fromNodeId: string
  toNodeId: string
  type: string
  data?: Record<string, any>
  order?: number
}

export type GraphPayload = { nodes: GraphNode[]; edges: GraphEdge[] }

export type RenderTreeNode = {
  /** Source graph node ID — repeats when a component is rendered more than once. Use for selection / live edits. */
  id: string
  /** Unique per position in the rendered tree. Use for React keys. */
  renderKey: string
  kind: 'element' | 'text' | 'fragment'
  tagHint: string | null
  props: Record<string, unknown>
  styleDeclarations: { property: string; value: string }[]
  children: RenderTreeNode[]
  metadata: Record<string, unknown>
}

export type ImportResult = {
  projectName: string
  graph: GraphPayload
  entryNodeId: string | null
  scriptCount: number
  stylesheetCount: number
}

export type Mutation =
  | { type: 'update_node_data'; projectId: string; nodeId: string; patch: Record<string, any> }
  | { type: 'rename_node'; projectId: string; nodeId: string; name: string }
  | { type: 'add_node'; projectId: string; node: GraphNode }
  | { type: 'add_edge'; projectId: string; edge: GraphEdge }
  | { type: 'remove_node'; projectId: string; nodeId: string }
  | { type: 'remove_edge'; projectId: string; edgeId: string }

// The Rust WASM surface takes/returns JSON strings rather than JS
// objects to avoid wasm-bindgen's re-entry check tripping when
// serde-wasm-bindgen walks JS values while the Engine holds a
// `&mut self` borrow. The cost is one JSON parse/stringify per call;
// the win is a contract identical to what iOS FFI will use.

function toJson(value: unknown, label: string): string {
  const s = JSON.stringify(value)
  if (typeof s !== 'string' || s.length === 0) {
    throw new Error(
      `engine.${label}: JSON.stringify produced ${typeof s === 'string' ? '""' : String(s)} for input ${String(value)}`,
    )
  }
  return s
}

export class Engine {
  private inner: WasmEngine

  constructor() {
    this.inner = new WasmEngine()
  }

  importFiles(projectName: string, files: FileBlob[]): ImportResult {
    return JSON.parse(this.inner.importFiles(projectName, toJson(files, 'importFiles')))
  }

  loadGraph(payload: GraphPayload): void {
    this.inner.loadGraph(toJson(payload, 'loadGraph'))
  }

  getGraph(): GraphPayload {
    return JSON.parse(this.inner.getGraph())
  }

  applyMutation(m: Mutation): unknown[] {
    return JSON.parse(this.inner.applyMutation(toJson(m, 'applyMutation')))
  }

  applyAgentOp(projectId: string, op: Record<string, any>): unknown[] {
    return JSON.parse(this.inner.applyAgentOp(projectId, toJson(op, 'applyAgentOp')))
  }

  walkRenderTree(rootId: string): RenderTreeNode | null {
    return JSON.parse(this.inner.walkRenderTree(rootId))
  }

  generateStylesheet(): { css: string; classesByElement: Record<string, string[]> } {
    return JSON.parse(this.inner.generateStylesheet())
  }

  buildSemanticLayer(projectId: string): { nodes: GraphNode[]; edges: GraphEdge[] } {
    return JSON.parse(this.inner.buildSemanticLayer(projectId))
  }

  buildUiLayer(projectId: string): { nodes: GraphNode[]; edges: GraphEdge[] } {
    return JSON.parse(this.inner.buildUiLayer(projectId))
  }
}

// ─────────────────────────────────────────────────────────────────────────
// Mini runtime — bindings for the standalone toggle-app runtime exposed by
// the Rust `mini-runtime` crate. Used by the MiniToggleApp React view to
// drive a real reactive UI off the graph.
// ─────────────────────────────────────────────────────────────────────────

export type MiniValue = null | boolean | number | string | { [k: string]: MiniValue }

export type MiniNodeKind =
  | 'component'
  | 'element'
  | 'atom'
  | 'token'
  | 'derived'
  | 'styleSheet'
  | 'cause'
  | 'effect'
  | 'doc'
  | 'ui'
  | 'repeat'

export interface MiniSemanticAnnotation {
  doc: string | null
  ui: string | null
}

export interface MiniRenderNode {
  id: string
  name: string
  kind: MiniNodeKind
  tag: string | null
  text: string | null
  attrs: Record<string, string>
  children: MiniRenderNode[]
  semantic: MiniSemanticAnnotation | null
}

export interface MiniEventBinding {
  element: string
  event: string
  cause: string
}

export interface MiniRuntimeSnapshot {
  designMode: boolean
  renderTree: MiniRenderNode
  styles: Record<string, Record<string, MiniValue>>
  atoms: Record<string, MiniValue>
  derived: Record<string, MiniValue>
  bindings: MiniEventBinding[]
  semanticNodes: Record<string, MiniSemanticAnnotation>
}

export type MiniPatch =
  | { type: 'atomChanged'; node: string; old: MiniValue; new: MiniValue }
  | { type: 'derivedChanged'; node: string; old: MiniValue; new: MiniValue }
  | { type: 'styleChanged'; element: string; property: string; old: MiniValue; new: MiniValue }
  | { type: 'eventHandled'; cause: string; effect: string }

export class MiniRuntime {
  private inner: WasmMiniRuntime
  constructor() {
    this.inner = new WasmMiniRuntime()
  }

  materialize(designMode: boolean): MiniRuntimeSnapshot {
    return JSON.parse(this.inner.materialize(designMode))
  }

  handleEvent(element: string, event: string): MiniPatch[] {
    return JSON.parse(this.inner.handleEvent(element, event))
  }

  /// Dispatch an event with a payload (typically the new value from a
  /// change event). Pass `undefined` for no payload.
  dispatchEvent(element: string, event: string, payload?: MiniValue): MiniPatch[] {
    const payloadJson = payload === undefined ? '' : JSON.stringify(payload)
    return JSON.parse(this.inner.dispatchEvent(element, event, payloadJson))
  }

  /// Replace the runtime's graph with a new payload (e.g. one returned by
  /// the LLM mini-app generator).
  loadGraph(payload: MiniGraphPayload): void {
    this.inner.loadGraph(JSON.stringify(payload))
  }

  /// Cypher-like text dump of the whole graph + current state.
  cypherDump(): string {
    return this.inner.cypherDump()
  }

  /// Current graph payload (round-trippable through loadGraph).
  graphPayload(): MiniGraphPayload {
    return JSON.parse(this.inner.graphPayload())
  }
}

// Wire-format graph payload. Mirrors the Rust GraphPayload shape; we keep
// it loose here (the runtime validates).
export interface MiniGraphPayload {
  root?: string | null
  nodes: any[]
  edges: any[]
}

export interface MiniGenerationResult {
  payload: MiniGraphPayload
  reasoning: string
  raw: string
}

/// Hit the server's /api/mini/generate endpoint and return the generated
/// graph payload. Server URL is fixed at localhost:4000 for v1.
export async function generateMiniApp(
  prompt: string,
  modelId?: string,
  baseUrl = 'http://localhost:4001',
): Promise<MiniGenerationResult> {
  const res = await fetch(`${baseUrl}/api/mini/generate`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ prompt, modelId }),
  })
  if (!res.ok) {
    const text = await res.text().catch(() => '')
    throw new Error(`generate failed (${res.status}): ${text}`)
  }
  return (await res.json()) as MiniGenerationResult
}
